### PR TITLE
Add ArchGDAL, HDF5, and NCDatasets compat entries to project.toml

### PR DESCRIPTION
**Pull request by vlandau**
In response to #66

### CODE REVIEW

**Comment by rafaqz** [comment]
I guess we could do that, and just not load them. The idea was you don't even have to install all of them (because these are really large binary deps). That's what the situation will be once Pkg has glue packages resolved.

But you would also need to put a line with the UUID in `[deps]`. Just adding the version there wont actually do what you want...
Also we should add HDF5.jl and NCDatasets.jl for consistency. 

I think we probably should actually, and switch back once Pkg has glue packages.

**Comment by vlandau** [comment]
Okay sounds good -- sorry I thought I saw a UUID for ArchGDAL already there. I'll add it now.

**Comment by rafaqz** [comment]
What about HDF5.jl and NCDatasets.jl... we probably can't just do one of the optional deps

**Comment by vlandau** [comment]
Ha :) was just commenting about those two but you beat me to it. I'm not sure the versions you want/need for HDF5.jl and NCDatasets.jl so I didn't add them yet.

**Comment by rafaqz** [comment]
Latest :)

**Comment by vlandau** [comment]
Feel free to scrap this PR if there are more significant changes that you need to make.

**Comment by rafaqz** [comment]
It should be fine. Thanks for the push

**Comment by vlandau** [comment]
Okay added those two -- should be good!

**Comment by rafaqz** [comment]
Sweet! I'll merge when travis approves

**Comment by rafaqz** [comment]
Lol Aqua.jl doesn't like GeoData having "Stale deps". I'll have to turn that check off

**Pull request merged**
